#! /bin/bash
#$ -r n
#$ -l h_rt=0:40:00
#$ -q daturamon.q
#$ -pe daturamon 12
#$ 
#$ -N bbh-0000
#$ -M barry.wardell@aei.mpg.de
#$ -m abe
#$ -o /lustre/datura/barry/simulations/EinsteinToolkit_Maxwell/bbh/output-0000/bbh.out
#$ -e /lustre/datura/barry/simulations/EinsteinToolkit_Maxwell/bbh/output-0000/bbh.err
#$ -cwd
#$ -R y
cd /home/barry/Cactus/EinsteinToolkit_Maxwell
/home/barry/Cactus/EinsteinToolkit_Maxwell/simfactory/bin/sim run bbh --machine=datura --restart-id=0 
