#! /bin/bash

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors

cd /lustre/datura/barry/simulations/EinsteinToolkit_Maxwell/bbh/output-0001-active

echo "Checking:"
pwd
hostname
date
cat ${MPI_NODEFILE} > SIMFACTORY/NODES

# This is necessary for the HDF5 installation, which requires that libimf be found
export LD_LIBRARY_PATH=/cluster/Compiler/Intel/11.1.072/lib/intel64:$LD_LIBRARY_PATH

echo "Environment:"
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=6
export MPIDIR=/cluster/openmpi/SL6/1.5.4/intel/11.1.072/
export MPI_NODEFILE=${TMPDIR}/machines
env | sort > SIMFACTORY/ENVIRONMENT

echo "Starting:"
uniq ${MPI_NODEFILE} > PROC_NODES
for node in $(cat PROC_NODES); do
    for (( proc=0; $proc<2; proc=$proc+1)); do
        echo ${node}
    done
done > ${MPI_NODEFILE}

export CACTUS_STARTTIME=$(date +%s)
time ${MPIDIR}/bin/mpirun -v --mca btl openib,self --mca mpi_leave_pinned 0 -np 2 -npernode 2 /lustre/datura/barry/simulations/EinsteinToolkit_Maxwell/bbh/SIMFACTORY/exe/cactus_sim -L 3 /lustre/datura/barry/simulations/EinsteinToolkit_Maxwell/bbh/output-0001/bbh.par

echo "Stopping:"
date

echo "Done."
