#! /bin/bash

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors

cd @RUNDIR@-active

echo "Checking:"
pwd
hostname
date

# This is necessary for the HDF5 installation, which requires that libimf be found
export LD_LIBRARY_PATH=/cluster/Compiler/Intel/11.1.072/lib/intel64:$LD_LIBRARY_PATH
echo "Environment:"
export CACTUS_NUM_PROCS=@NUM_PROCS@
export CACTUS_NUM_THREADS=@NUM_THREADS@
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=@NUM_THREADS@
export MPIDIR=/cluster/openmpi/SL6/1.5.4/intel/11.1.072/

if [ ! -z "$MPI_NODEFILE" ]; then
    cat ${MPI_NODEFILE} > SIMFACTORY/NODES
    export MPI_NODEFILE=${TMPDIR}/machines

    uniq ${MPI_NODEFILE} > PROC_NODES

    for node in $(cat PROC_NODES); do
        for (( proc=0; $proc<@(@PPN_USED@/@NUM_THREADS@)@; proc=$proc+1)); do
            echo ${node}
        done
    done > ${MPI_NODEFILE}
fi

env | sort > SIMFACTORY/ENVIRONMENT

export CACTUS_STARTTIME=$(date +%s)
echo "Starting:"
time ${MPIDIR}/bin/mpirun -v --mca btl openib,self --mca mpi_leave_pinned 0 -np @NUM_PROCS@ -npernode @(@PPN_USED@/@NUM_THREADS@)@ @EXECUTABLE@ -L 3 @PARFILE@

echo "Stopping:"
date

echo "Done."
