#! /bin/bash

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors

cd /lustre/datura/ianhin/simulations/test7patch/output-0000-active

echo "Checking:"
pwd
hostname
date

# This is necessary for the HDF5 installation, which requires that libimf be found
export LD_LIBRARY_PATH=/cluster/Compiler/Intel/11.1.072/lib/intel64:$LD_LIBRARY_PATH
echo "Environment:"
export CACTUS_NUM_PROCS=12
export CACTUS_NUM_THREADS=1
export GMON_OUT_PREFIX=gmon.out
export OMP_NUM_THREADS=1
export MPIDIR=/cluster/openmpi/SL6/1.5.4/intel/11.1.072/

if [ ! -z "$MPI_NODEFILE" ]; then
    cat ${MPI_NODEFILE} > SIMFACTORY/NODES
    export MPI_NODEFILE=${TMPDIR}/machines

    uniq ${MPI_NODEFILE} > PROC_NODES

    for node in $(cat PROC_NODES); do
        for (( proc=0; $proc<12; proc=$proc+1)); do
            echo ${node}
        done
    done > ${MPI_NODEFILE}
fi

env | sort > SIMFACTORY/ENVIRONMENT

export CACTUS_STARTTIME=$(date +%s)
echo "Starting:"
time ${MPIDIR}/bin/mpirun -v --mca btl openib,self --mca mpi_leave_pinned 0 -np 12 -npernode 12 /lustre/datura/ianhin/simulations/test7patch/SIMFACTORY/exe/cactus_sim -L 3 /lustre/datura/ianhin/simulations/test7patch/output-0000/test7patch.par

echo "Stopping:"
date

echo "Done."
